name: "JSON to CSV Converter"
description: "Converts a JSON file to CSV format and stores it in the specified location"
inputs:
  input-file:
    description: "The JSON file to be converted"
    required: true
  output-file:
    description: "The path where the CSV file will be saved"
    required: true
  GITHUB_TOKEN:
    description: "Github token"
    required: true
  
runs:
  using: "composite"
  steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        shell: bash
        run: npm install
        working-directory: .github/actions/json-to-csv-action # Adjust this path as needed

      - name: Run script
        shell: bash
        env: 
          input-file: ${{ inputs.input-file }}
          output-file: ${{ inputs.output-file }}
        run: node ./.github/actions/json-to-csv-action/index.js

      - name: Commit and Push CSV
        shell: bash
        if: success()
        run: |
          echo ${{ inputs.output-file }}
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
   
          git status
          git add ${{ inputs.output-file }}
          git commit -m "Add converted CSV file from JSON"
          git push
        env:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
               

  # Step 3: Run the main script
    #- name: Run JSON to CSV script
    #  run: node index.js
    #  shell: bash
    #  working-directory: .github/actions/json-to-csv-action # Adjust this path as needed
    #  with:
    #    input-file: ${{ inputs.input-file }}
    #    output-file: ${{ inputs.output-file }}
