name: "JSON to CSV Converter"
description: "Converts a JSON file to CSV format and stores it in the specified location"
inputs:
  input_file:
    description: "The JSON file to be converted"
    required: true
  output_file:
    description: "The path where the CSV file will be saved"
    required: true
  GITHUB_TOKEN:
    description: "Github token"
    required: true
  
runs:
  using: "composite"
  steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      #- name: Authenticate with npm registry
      #  uses: actions/setup-node@v2
      #  with:
      #    node-version: '16'
      #    registry-url: $NPM_REGISTRY_URL
      #    scope: '@your-scope'
      #  env:
      #    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      #- name: Install dependencies
      #  shell: bash
      #  run: npm install
      #  working-directory: .github/actions/json-to-csv-action 

      - name: Install NPM Dependencies
        shell: bash
        run: |
          export PATH=$PATH:${{ vars.NODE_PATH }}
          npm config set registry ${{ vars.NPM_REGISTRY_URL }}
          npm config set _auth ${{ secrets.NPM_AUTH}}
          npm config set always-auth true
          npm config set cafile '/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem'
          npm config set email ${{ vars.NPM_USER_EMAIL }}
          npm install
        working-directory: .github/actions/json-to-csv-action 

      - name: Run script
        shell: bash
        env: 
          input-file: ${{ inputs.input_file }}
          output-file: ${{ inputs.output_file }}
        run: node ./.github/actions/json-to-csv-action/index.js

      - name: Commit and Push CSV
        shell: bash
        env:
         GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
         OUTPUT_FILE:  ${{ inputs.output_file }}
        if: success()
        run: |
          echo "The output file is: $OUTPUT_FILE"
          cat $OUTPUT_FILE
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          realpath $OUTPUT_FILE
          pwd
          git status
          git add $OUTPUT_FILE
          git commit -m "Add converted CSV file from JSON"
          git push
       
               

  # Step 3: Run the main script
    #- name: Run JSON to CSV script
    #  run: node index.js
    #  shell: bash
    #  working-directory: .github/actions/json-to-csv-action # Adjust this path as needed
    #  with:
    #    input-file: ${{ inputs.input-file }}
    #    output-file: ${{ inputs.output-file }}
