name: "JSON to CSV Converter"
description: "Converts a JSON file to CSV format and stores it in the specified location"
inputs:
  input-file:
    description: "The JSON file to be converted"
    required: true
  output-file:
    description: "The path where the CSV file will be saved"
    required: true
runs:
  using: "composite"
  steps:
    # Step 1: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Step 2: Install dependencies
    - name: Install dependencies
      run: npm install
      working-directory: .github/actions/json-to-csv-action # Adjust this path as needed

  # Step 3: Run the main script
    - name: Run JSON to CSV script
      run: node index.js
      working-directory: .github/actions/json-to-csv-action # Adjust this path as needed
      with:
        input-file: ${{ inputs.input-file }}
        output-file: ${{ inputs.output-file }}
